
#Client side changes.
[client]
	#Disable the 1.9+ combat sounds.
	disableCombatSounds = true
	#Removes environmental fog from the Nether Dimension.
	disableNetherFog = true
	#Enable the classic menu. (May cause mod compatibility issues when used with other menu mods)
	enableClassicMenu = true
	#The maximum distance fog can be toggled to.
	toggleFogMaxDistance = 16
	#Gives the classic HUD, removing the hunger bar, and adjusting the position of armor bar.
	oldHud = true
	#Enable custom dimension entry messages. (Vanilla Dimensions)
	customDimensionMessages = true
	#The height offset of the hearts when using the old HUD.
	heartHeight = 32
	#Displays Minecraft version at the top of screen when in game.
	oldIngameVersion = true

